server:
  port: 80 #端口
spring:
  application:
    name: FreeMarker #服务名
  freemarker:
    cache: false #关闭模板缓存，便于测试
    settings:
      template_update_delay: 0  #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
    suffix: .ftl  #FreeMarker模板文件后缀
    # ！！！ freemarker模板文件通常都是以ftl作为扩展名,也可以为html、xml、jsp等





